APP_NAME = "SCAMVERSE"
APP_VERSION = "3.0"
APP_SUBTITLE = "Online Investment Scam Ecosystem Intelligence Platform"
FRAMEWORK_NAME = "Integrated Multi-Stakeholder Prevention Framework (IMSPF)"
PRIMARY_COLOR = "#2563EB"
SECONDARY_COLOR = "#9333EA"
ACCENT_COLOR = "#06B6D4"
